name: build and test

on:
  push:
    branches: [ master, Rel* ]
  pull_request:
    branches: [ master, Rel* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Build with dotnet
      working-directory: ./CyborgianStates.Tests
      run: |
        dotnet build ../CyborgianStates/CyborgianStates.sln
        # temporary: copy settings so tests pass. this should be removed before release
        cp ../CyborgianStates/appsettings.json bin/Debug/net5.0/appsettings.development.json
    - name: Run tests
      working-directory: ./CyborgianStates.Tests
      run: |
        dotnet tool install --global coverlet.console
        ~/.dotnet/tools/coverlet bin/Debug/net5.0/CyborgianStates.Tests.dll --target "dotnet" --targetargs "test --no-build" --exclude "[*]CyborgianStates.MessageHandling.ConsoleInput" --exclude "[*]CyborgianStates.AppSettings" --exclude "[*]CyborgianStates.Data.Models.*" --exclude "[*]CyborgianStates.Data.SqliteSqlProvider" --exclude "[*]CyborgianStates.MessageHandling.DiscordClientWrapper" --exclude "[*]CyborgianStates.BotEnvironment" --exclude "[*]*.Exceptions.*" --format opencover --output "./TestResults//"
    - name: Upload coverage to codecov.io
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./CyborgianStates.Tests/TestResults/coverage.opencover.xml
        fail_ci_if_error: false